import 'package:flutter/material.dart';

class ChartData {
  final String name;
  final double percent;
  final Color color;

  ChartData({this.name, this.percent, this.color});
}

class Category {
  final String id;
  final String title;
  final Color color;
  final String image;

  const Category({
    this.id,
    this.title,
    this.color,
    this.image,
  });
}

Map<String, dynamic> languages = {
  'en': AppLanguage.enLang,
  'my': AppLanguage.myLang,
  'ch': AppLanguage.chLang,
  'ru': AppLanguage.ruLang,
  'vn': AppLanguage.vnLang,
  'th': AppLanguage.thLang,
};

class AppLanguage {
  static const Map<String, Object> enLang = {
    'testing': "Testing",
    'code': "en",
    'name': "english",
    'image': "assets/images/en.png",
    'title': "NGAVITT",
    'totalcases': "Total Cases",
    'todaycases': "Today Cases",
    'totalrecovered': "Total Recovered",
    'todayrecovered': "Today Recovered",
    'totaldeath': "Total Death",
    'todaydeath': "Today Death",
    'activecases': "Active Cases",
    'criticalcases': "Critical Cases",
    'refreshcases': "Refresh Cases",
    'seeallcountries': "See All Countries",
    'allcountries': "All Countries",
    'sortbyName': "Sort by name",
    'sortbytotalcases': "Sort by total case",
    'sortbyactivecases': "Sort by active case",
    'bydescending': "By descending",
    'byascending': "By ascending",
    'seeallstatus': "See all status",
    'preventions': "Preventions",
    'globalpiechart': "Global PieChart",
    'contactme': "Contact Me",
    'countries': "Countries",
    'continents': "Continents",
    'people': "People",
    'changelanguage': "Change Language",
    'asia': "Asia",
    'africa': "Africa",
    'europe': "Europe",
    'northamerica': "North America",
    'southamerica': "South America",
    'australia': "Australia-Oceania",
    'searchcountrybyname': "search country by name ...",
    'nocountriesfounded': "No Countries Founded!",
    'preventionsWays': {
      'title': 'Preventions',
      'dail': 'Dial 999 for \nMedical Help!\n',
      'symptoms': 'If any symptoms appear',
      'washHands': 'Wash Hands',
      'wearMasks': 'Wear Masks',
      'cleaning': 'Clean Disinfect',
    },
    'globalPieChart': {
      'title': "Global Chart Status",
      'active': "Active Percentage",
      'recovered': "Recovered Percentage",
      'comfirmed': "Comfirmed Percentage",
    }
  };

  static const myLang = {
    'testing': "စမ္းသပ္မွူ",
    'code': "my",
    'name': "myanmar",
    'image': "assets/images/my.png",
    'title': "ငဗစ်",
    'totalcases': "စုစုပေါင်းဖြစ်စဉ်",
    'todaycases': "ယနေ့ဖြစ်စဉ်",
    'totalrecovered': "ပျောက်ကင်းပေါင်း",
    'todayrecovered': "ယနေ့ပျောက်ကင်း",
    'totaldeath': "စုစုပေါင်းသေဆုံး",
    'todaydeath': "ယနေ့သေဆုံး",
    'activecases': "လက်ကျန်လူနာ",
    'criticalcases': "အရေးကြီးလူနာ",
    'refreshcases': "ပြန်စစ်မယ်",
    'seeallcountries': "နိုင်ငံအားလုံးကြည့်မယ်",
    'allcountries': "နိုင်ငံအားလုံး",
    'sortbyName': "နာမည်အလိုက်စီမယ်",
    'sortbytotalcases': "ဖြစ်စဉ်အလိုက်စီမယ်",
    'sortbyactivecases': "လက်ကျန်အလိုက်စီမယ်",
    'bydescending': "ပြောင်းပြန်လိုက်",
    'byascending': "အတည့်တိုင်း",
    'seeallstatus': "အားလုံး ကြည့်မယ်",
    'preventions': "ကာကွယ်နည်းများ",
    'globalpiechart': "ကမ္ဘာ့အခြေအနေ",
    'contactme': "ကျနေ့ာကိုဆယ်သွယ်",
    'countries': "နိုင်ငံအလိုက်",
    'continents': "တိုက်ကြီးအလိုက်",
    'people': "ယောက်",
    'changelanguage': "ဘာသာစကားပြောင်းမယ်",
    'asia': "အာရှ",
    'africa': "အာဖရိက",
    'europe': "ဥရောပ",
    'northamerica': "မြောက်အမေရိက",
    'southamerica': "တောင်အမေရိက",
    'australia': "ဩစတေးလျ",
    'searchcountrybyname': "နိုင်ငံကိုနာမည်ရိုက် ရှာဖွေပါ ...",
    'nocountriesfounded': "ဘယ်နိုင်ငံမှ ရှာမတွေ့ပါ!",
    'preventionsWays': {
      'title': 'Preventions',
      'dail': 'အကူညီလိုရင်\n ၉၉၉ ကို\n',
      'symptoms': 'ဆက်သွယ်လိုက်ပါ',
      'washHands': 'mask ဆေးပါ',
      'wearMasks': 'လက်တပ်ပါ',
      'cleaning': 'သန့်ရှင်းရေးလုပ်ပါ',
    },
    'globalPieChart': {
      'title': "ကမ္ဘာ့အခြေအနေ",
      'active': "လက်ရှိလူနာရာခိုင်နှုန်း",
      'recovered': "ပျောက်ကင်းသူရာခိုင်နှုန်း",
      'comfirmed': "စုစုပေါင်းရာခိုင်နှုန်း",
    }
  };

  static const chLang = {
    'testing': "测试",
    'code': "ch",
    'name': "china",
    'image': "assets/images/ch.jpg",
    'title': "恩加维特",
    'totalcases': "总病例数",
    'todaycases': "今日案例 ",
    'totalrecovered': "总恢复",
    'todayrecovered': "今天康复",
    'totaldeath': "完全死亡",
    'todaydeath': "今天死亡",
    'activecases': "现有病例",
    'criticalcases': "危急情况",
    'refreshcases': "刷新案例",
    'seeallcountries': "查看所有国家",
    'allcountries': "所有国家",
    'sortbyName': "按名称分类",
    'sortbytotalcases': "按病例总数排序",
    'sortbyactivecases': "按活动案例排序",
    'bydescending': "通过下降",
    'byascending': "通过上升",
    'seeallstatus': "查看所有状态",
    'preventions': "预防方法",
    'globalpiechart': "预防措施",
    'contactme': "联系开发商",
    'countries': "按国家/地区",
    'continents': "各大洲",
    'people': "人们",
    'changelanguage': "改变语言",
    'asia': "亚洲",
    'africa': "非洲",
    'europe': "欧洲",
    'northamerica': "北美",
    'southamerica': "南美洲",
    'australia': "澳大利亚",
    'searchcountrybyname': "输入国家名称 ...",
    'nocountriesfounded': "没有国家成立！",
    'preventionsWays': {
      'title': '预防措施',
      'dail': '拨打 999 \n医疗帮助！\n',
      'symptoms': '如果出现任何症状',
      'washHands': '洗手',
      'wearMasks': '戴口罩',
      'cleaning': '清洁消毒',
    },
    'globalPieChart': {
      'title': "全球图表状态",
      'active': "活跃百分比",
      'recovered': "恢复百分比",
      'death': "死亡百分比",
    }
  };

  static const ruLang = {
    'testing': "Эксперимент",
    'code': "ru",
    'name': "russia",
    'image': "assets/images/ru.png",
    'title': "Нгавитт",
    'totalcases': "Всего случаев",
    'todaycases': "Сегодня кейсы",
    'totalrecovered': "Всего восстановлено",
    'todayrecovered': "Сегодня восстановлено",
    'totaldeath': "Полная смерть",
    'todaydeath': "Сегодня смерть",
    'activecases': "Активные случаи",
    'criticalcases': "Критические случаи",
    'refreshcases': "Обновить обращения",
    'seeallcountries': "Посмотреть все страны",
    'allcountries': "Все страны",
    'sortbyName': "Сортировать по имени",
    'sortbytotalcases': "Сортировать по общему",
    'sortbyactivecases': "Сортировать по активным",
    'bydescending': "По убыванию",
    'byascending': "По возрастанию",
    'seeallstatus': "Посмотреть все статусы",
    'preventions': "Профилактика",
    'globalpiechart': "мировая ситуация",
    'contactme': "Свяжитесь со мной",
    'countries': "по странам",
    'continents': "по континентам",
    'people': "мужчина",
    'changelanguage': "изменение языка",
    'asia': "Азия",
    'africa': "Африке",
    'europe': "Европа",
    'northamerica': "Северная Америка",
    'southamerica': "Южная Америка",
    'australia': "Австралия",
    'searchcountrybyname': "Искать страну по названию ...",
    'nocountriesfounded': "Странане найдена!",
    'preventionsWays': {
      'title': 'Preventions',
      'dail': 'когда нужна помощь\n #999 K\n',
      'symptoms': 'Связаться с нами',
      'washHands': 'Вымой руки',
      'wearMasks': 'Носить маски',
      'cleaning': 'Сделай уборку',
    },
    'globalPieChart': {
      'title': "Мировая ситуация",
      'active': "Текущий процент пациентов",
      'recovered': "Процент излеченных",
      'death': "Процент cмерть",
    }
  };

  static const vnLang = {
    'testing': "Testing",
    'code': "vn",
    'name': "vietnam",
    'image': "assets/images/vn.png",
    'title': "NGAVITT",
    'totalcases': "Toàn bộ",
    'todaycases': "Hôm nay",
    'totalrecovered': "Phục hồi",
    'todayrecovered': "Mới Phục Hồ",
    'totaldeath': "Cái chết",
    'todaydeath': "Cái chết mới",
    'activecases': "Hiện hành",
    'criticalcases': "Phê bình",
    'refreshcases': "Làm mới",
    'seeallcountries': "Tất cả các nước",
    'allcountries': "Tất cả các nước",
    'sortbyName': "bằng tên",
    'sortbytotalcases': "với tổng số",
    'sortbyactivecases': "với hoạt động",
    'bydescending': "giảm dần",
    'byascending': "tăng dần",
    'seeallstatus': "Nhìn thấy tất cả",
    'preventions': "Phòng ngừa",
    'globalpiechart': "Biểu đồ toàn cầu",
    'contactme': "Liên hệ với tôi",
    'countries': "Theo quốc gia",
    'continents': "Bởi lục địa",
    'people': "Mọi người",
    'changelanguage': "Thay đổi ngôn ngữ",
    'asia': "Châu Á",
    'africa': "Châu phi",
    'europe': "Châu Âu",
    'northamerica': "Bắc Mỹ",
    'southamerica': "Nam Mỹ",
    'australia': "Châu Úc",
    'searchcountrybyname': "tìm kiếm theo tên ...",
    'nocountriesfounded': "không kết quả",
    'preventionsWays': {
      'title': 'Phòng ngừa',
      'dail': 'Quay số 999 cho \nTrợ giúp y tế!\n',
      'symptoms': 'Nếu bất kỳ triệu chứng nào xuất hiện',
      'washHands': 'Rửa tay',
      'wearMasks': 'Đeo mặt nạ',
      'cleaning': 'Làm sạch',
    },
    'globalPieChart': {
      'title': "Bởi toàn cầu",
      'active': "Tích cực thu hồi",
      'recovered': "Phần trăm thu hồi",
      'death': "Tỷ lệ tử vong",
    }
  };

  static const thLang = {
    'testing': "การทดสอบ",
    'code': "th",
    'name': "thailand",
    'image': "assets/images/th.jpeg",
    'title': "งาวิท",
    'totalcases': "รวมคดี",
    'todaycases': "เคสวันนี้",
    'totalrecovered': "ฟื้นแล้ว",
    'todayrecovered': "วันนี้ฟื้นแล้ว",
    'totaldeath': "เสียชีวิตทั้งหมด",
    'todaydeath': "วันนี้ความตาย",
    'activecases': "คล่องแคล่ว",
    'criticalcases': "คดีสาคัญ",
    'refreshcases': "รีเฟรชเคส",
    'seeallcountries': "ดูประเทศทัง ้หมด",
    'allcountries': "ทุกประเทศ",
    'sortbyName': "เรียงตามชอ ื่",
    'sortbytotalcases': "เรียงตามกรณีทง ั",
    'sortbyactivecases': "เรียงตามเคสทีใ ่",
    'bydescending': "โดยการลง",
    'byascending': "โดยขึ้น",
    'seeallstatus': "ดูสถานะทั้งหมด",
    'preventions': "การป้องกัน",
    'globalpiechart': "สถานการณ์โลก",
    'contactme': "ติดต่อฉันวันนี้",
    'countries': "ตามประเทศ",
    'continents': "ตามทวีป",
    'people': "ผู้คน",
    'changelanguage': "เปลี่ยนภาษา",
    'asia': "เอเชีย",
    'africa': "แอฟริกา",
    'europe': "ยุโรป",
    'northamerica': "อเมริกาเหนือ",
    'southamerica': "อเมริกาใต้",
    'australia': "ออสเตรเลีย",
    'searchcountrybyname': "ค้นหาตามประเทศ ...",
    'nocountriesfounded': "ไม่พบประเทศ!",
    'preventionsWays': {
      'title': 'Preventions',
      'dail': 'ถ้าคุณต้องการความช่วยเหลือ\n #999 \n',
      'symptoms': 'ติดต่อเรา',
      'washHands': 'ล้างมือ',
      'wearMasks': 'สวมหน้ากาก',
      'cleaning': 'ทำความสะอาด',
    },
    'globalPieChart': {
      'title': "สถานการณ์โลก",
      'active': "ร้อยละปัจจุบันของผู้ป่วย",
      'recovered': "เปอร์เซ็นต์การรักษา",
      'death': "อัตราการเสียชีวิต",
    }
  };
}
